AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Metadata"
          AttributeType: "S"
        - 
          AttributeName: "Requests"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "Metadata"
          KeyType: "HASH"
        - 
          AttributeName: "Requests"
          KeyType: "STRING"
Outputs:
  TableName:
    Value: !Ref 'myDynamoDBTable'
    Description: Table name of the newly created DynamoDB table
